### ISSUE TITLE
多模块打 jar ,war包

### ISSUE THREAD

**Issue by QingHui653** [xiaomoinfo/SpringBootUnity#2]
我想请问一下多模块boot 项目如果打 jar 包 或 war包，我的boot项目，使用install 无法打包成功。

具体为引用的mybatis 模块 打为jar包 无法扫描到。
![Uploading image.png…]()

![Uploading image.png…]()

**Comment by syoubaku** [comment]
没明白你说的是什么意思。你引的mybatis是我项目的mybatis模块还是官方的mybatis依赖包。

**Comment by QingHui653** [comment]
使用的是官方的，我service在mybatis 中，打包为jar
![Uploading image.png…]()

 , mybatis模块也打为jar包，启动时，spring扫描不到service注解，导致
![Uploading image.png…]() ，引用不了mybatis模块。

**Comment by syoubaku** [comment]
我的这个项目中也有引用到mybatis的，仔细对照一下看看哪里出了问题

**Comment by QingHui653** [comment]
已经解决了，谢谢。
